### PR TITLE
CC-1227 Change slug to legacy slug

### PR DESCRIPTION
**Pull request by libmartinito**

### CODE REVIEW

**Comment by libmartinito** [comment]
can you please confirm if it's fine to ignore breaking tests for now

**Comment by rohitpaulk** [comment]
@libmartinito there are failing tests here

**Comment by rohitpaulk** [comment]
> can you please confirm if it's fine to ignore breaking tests for now

@libmartinito the failures seem related to this change though - so we'll need them to eventually be passing. If you've got a plan to keep the disruption minimal and only have this failing for an hour or so, that's fine - else we'll need to find a more backward-compatible solution.

**Review by rohitpaulk — DISMISSED** [review]
Let's have clarity on how we're going to handle test failures, and how long they'll last

**Comment by libmartinito** [comment]
to avoid making changes to tester versions at this stage, what do you think of keeping around slug? then instead of checking if there are no null course stage slug values in the next stage, we'd check if they're in the correct format?

**Review by rohitpaulk — APPROVED** [review]

**Pull request merged**
